[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
runner = "esp-flash flash --monitor"
rustflags = [
    "-C", "force-frame-pointers",
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "debug"
